replicaCount: 1

image:
  repository: ghcr.io/loukjeab/eulynx_sdi_opc_ua_bl4r3/server
  pullPolicy: IfNotPresent
  tag: v1

service:
  type: NodePort  # Set service type to NodePort
  ports:
    - name: pointgroup-ffm
      port: 4840
      targetPort: 4840
      nodePort: 30040  # Explicit NodePort
    - name: pointgroup-muc
      port: 4841
      targetPort: 4841
      nodePort: 30041
    - name: pointgroup-ber
      port: 4842
      targetPort: 4842
      nodePort: 30042
    - name: pointgroup-ham
      port: 4843
      targetPort: 4843
      nodePort: 30043
    - name: pointgroup-dus
      port: 4844
      targetPort: 4844
      nodePort: 30044
    - name: pointgroup-emd
      port: 4845
      targetPort: 4845
      nodePort: 30045
    - name: pointgroup-koln
      port: 4846
      targetPort: 4846
      nodePort: 30046
    - name: pointgroup-strabourg
      port: 4847
      targetPort: 4847
      nodePort: 30047

servers:
  - name: pointgroup-ffm
    port: 4840
    endpoint: opc.tcp://0.0.0.0:4840/EULYNX
  - name: pointgroup-muc
    port: 4841
    endpoint: opc.tcp://0.0.0.0:4841/EULYNX
  - name: pointgroup-ber
    port: 4842
    endpoint: opc.tcp://0.0.0.0:4842/EULYNX
  - name: pointgroup-ham
    port: 4843
    endpoint: opc.tcp://0.0.0.0:4843/EULYNX
  - name: pointgroup-dus
    port: 4844
    endpoint: opc.tcp://0.0.0.0:4844/EULYNX
  - name: pointgroup-emd
    port: 4845
    endpoint: opc.tcp://0.0.0.0:4845/EULYNX
  - name: pointgroup-koln
    port: 4846
    endpoint: opc.tcp://0.0.0.0:4846/EULYNX
  - name: pointgroup-strabourg
    port: 4847
    endpoint: opc.tcp://0.0.0.0:4847/EULYNX


serviceAccount:
  create: true
  automount: true
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
