apiVersion: v1
kind: Service
metadata:
  name: opc-ua-server-service
spec:
  selector:
    app: opc-ua-server
  ports:
    - protocol: TCP
      port: 4840
      targetPort: 4840
  type: LoadBalancer  # or NodePort if running locally
