apiVersion: v1
kind: Service
metadata:
  name: opcua-servers-service
spec:
  selector:
    app: opcua-servers
  ports:
    {{- range $server := .Values.service.ports }}
    - name: {{ $server.name }}
      protocol: TCP
      port: {{ $server.port }}
      targetPort: {{ $server.targetPort }}
      nodePort: {{ $server.nodePort }}
    {{- end }}
  type: {{ .Values.service.type }}  # This will be NodePort
